name: lint
on: [push, pull_request]
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  lint:
    name: tox-${{ matrix.toxenv }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        toxenv: [lint, docs-lint, pycodestyle]
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Using Python ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --index-url 'https://:2023-07-19T11:46:44.510643Z@time-machines-pypi.sealsecurity.io/' --upgrade pip
          python -m pip install --index-url 'https://:2023-07-19T11:46:44.510643Z@time-machines-pypi.sealsecurity.io/' tox
      - run: tox -e ${{ matrix.toxenv }}
