name: tox
on: [push, pull_request]
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  tox:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest] # All OSes pass except Windows because tests need Unix-only fcntl, grp, pwd, etc.
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.8" ]
        exclude:
          - os: macos-latest
            python-version: 3.7
    steps:
      - uses: actions/checkout@v3
      - name: Using Python ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --index-url 'https://:2023-07-19T11:46:44.510643Z@time-machines-pypi.sealsecurity.io/' --upgrade pip
          python -m pip install --index-url 'https://:2023-07-19T11:46:44.510643Z@time-machines-pypi.sealsecurity.io/' tox
      - run: tox -e py
